const config = {
  back: "http://localhost:5555",
  api: "http://localhost:5556",
  BATTERY_CHART_UPDATE_TIMEOUT: 1000,
  BATTERY_CHART_REALTIME_MAX_ITEMS: 10,
  CMD_TIMEOUT: 5,
  NOTIFICATION_DURATION: 3000,
  BATTERY_CHART_MAX_ITEMS: 120,
  TOPOLOGY_EDGES_LENGTH: 150,
  EVENTS_CHART_REALTIME_MAX_ITEMS: 10,
  EVENTS_CHART_UPDATE_TIMEOUT: 5000,
  EVENTS_CHART_MAX_ITEMS: 120,
  STATS_CHART_UPDATE_TIMEOUT: 10000,
  STATS_CHART_MAX_ITEMS: 50,
  STATS_CHART_REALTIME_MAX_ITEMS: 10,
};

export default config;